imports:
- { resource: config_dev.yml }
- { resource: parameters.yml }

liip_functional_test:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.sqlite"
                charset:  UTF8

security:
    firewalls:
        main:
            pattern: ^/
            http_basic: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
