imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    use_microseconds: false
    handlers:
        main:
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ['!event', '!doctrine', '!console', '!translation']
        console:
            type:   console
            channels: ['!event', '!doctrine', '!console', '!translation']
