imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "../../vendor/beberlei/DoctrineExtensions/config/mysql.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator:
        enabled: true
        logging: false
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path:   ~
        name: PHP_SESSION_SEN
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'
        cookie_secure: '%secure_cookies%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
    - 'bootstrap_3_horizontal_layout.html.twig'
    - 'NinesUtilBundle:form:fields.html.twig'
    - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
    - '::jquery.collection.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.root_dir%/../src/Nines/UtilBundle/Resources/views': NinesUtilBundle
    exception_controller:  NinesUtilBundle:Error:showException
    globals:
        comment_service: "@feedback.comment"
    date:
        format: d M Y
        interval_format: '%%d days'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

sensio_framework_extra:
    router:
        annotations: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nines\UserBundle\Entity\User
    profile:
        form:
            type: Nines\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Nines\UserBundle\Form\PasswordType
    from_email:
        address: noreply@dhil.lib.sfu.ca
        sender_name: WPHP User Manager

fos_ck_editor:
    input_sync: true
    default_config: wphp_config
    configs:
        wphp_config:
            entities: false
            toolbar: standard

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig

nines_feedback:
    default_status: submitted
    public_status: published
    commenting:
        firm:
            class: AppBundle\Entity\Firm
            route: firm_show
        person:
            class: AppBundle\Entity\Person
            route: person_show
        title:
            class: AppBundle\Entity\Title
            route: title_show
        blog_post:
            class: Nines\BlogBundle\Entity\Post
            route: post_show
        blog_page:
            class: Nines\BlogBundle\Entity\Page
            route: page_show

nines_blog:
    default_status: draft
    default_category: none

nines_user:
    permission_levels: [ ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN ]
